# Numpy

In [2]:
import numpy as np

In [8]:
x=np.array([1,2,3,4,5,6,7,8,9])
y=numpy.arange(10,50)
print(x)
print(y)

[1 2 3 4 5 6 7 8 9]
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [9]:
np.__version__

'1.14.3'

In [14]:
from numpy import array
a=array([1,2,3,4])
print(a)

[1 2 3 4]


In [16]:
# For importing all func from numpy
from numpy import *
a=arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


## Numpy Array Creation Format
- list
- tuple
- range

In [20]:
print(np.array([313,13,54]))

[313  13  54]


In [23]:
print(np.array((2,3,4)))

[2 3 4]


In [28]:
print(np.arange(10))

[0 1 2 3 4 5 6 7 8 9]


In [33]:
x=np.array(range(5,10))
print(x)
type(x)

[5 6 7 8 9]


numpy.ndarray

In [44]:
print(x.shape)  #tuple
print(x.dtype)  #data type
print(x.size)   #no of elements
print(x.itemsize) #no of bytes for each items
print(x.ndim)   #no of dimensions
print(x.nbytes)  #ntotal no of bytes in array

(5,)
int32
5
4
1
20


In [42]:
l=[1]
t=(1)
print(l)
print(t)
type(l)
type(t)

[1]
1


int

In [50]:
a=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print(a.shape)  #tuple
print(a.dtype)  #data type
print(a.size)   #no of elements
print(a.itemsize) #no of bytes for each items
print(a.ndim)   #no of dimensions
print(a.nbytes) 
print(a.shape[0])  #no of rows
print(a.shape[1])  #no of coloumns

(4, 3)
int32
12
4
2
48
4
3


In [53]:
np.array([1,2,3,7],dtype=np.int8)

array([1, 2, 3, 7], dtype=int8)

In [55]:
a=np.array([1,2,3,7,(2**32)+1])
print(a.dtype)

int64


In [56]:
a1=np.array([1,2,3,7,'python'])
print(a1.dtype)

<U11


In [57]:
a1=np.array([1,2,3,7,None])
print(a1.dtype)

object


In [58]:
a1=np.array([1,2,3,7,np.nan])
print(a1.dtype)

float64


In [59]:
help(np.ones)

Help on function ones in module numpy.core.numeric:

ones(shape, dtype=None, order='C')
    Return a new array of given shape and type, filled with ones.
    
    Parameters
    ----------
    shape : int or sequence of ints
        Shape of the new array, e.g., ``(2, 3)`` or ``2``.
    dtype : data-type, optional
        The desired data-type for the array, e.g., `numpy.int8`.  Default is
        `numpy.float64`.
    order : {'C', 'F'}, optional
        Whether to store multidimensional data in C- or Fortran-contiguous
        (row- or column-wise) order in memory.
    
    Returns
    -------
    out : ndarray
        Array of ones with the given shape, dtype, and order.
    
    See Also
    --------
    zeros, ones_like
    
    Examples
    --------
    >>> np.ones(5)
    array([ 1.,  1.,  1.,  1.,  1.])
    
    >>> np.ones((5,), dtype=int)
    array([1, 1, 1, 1, 1])
    
    >>> np.ones((2, 1))
    array([[ 1.],
           [ 1.]])
    
    >>> s = (2,2)
    >>> np.ones(s)
    ar

In [62]:
c=(3,3,3)
np.ones(c)

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [72]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [69]:
np.ones((2,3),bool)

array([[ True,  True,  True],
       [ True,  True,  True]])

## Initializing Arrays
- Zeroes
- Ones
- full
- eye
- diag

## Creating arrays in arange 
- arange
- inspace

In [73]:
np.arange(10,100,5)

array([10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90,
       95])

In [74]:
np.arange(5,10,0.5)

array([5. , 5.5, 6. , 6.5, 7. , 7.5, 8. , 8.5, 9. , 9.5])

In [76]:
np.linspace(5,10,10)

array([ 5.        ,  5.55555556,  6.11111111,  6.66666667,  7.22222222,
        7.77777778,  8.33333333,  8.88888889,  9.44444444, 10.        ])

In [80]:
s='human'
byte=b'hii'
print(s,byte)
type(byte)

human b'hii'


bytes

In [81]:
help(bytes)

Help on class bytes in module builtins:

class bytes(object)
 |  bytes(iterable_of_ints) -> bytes
 |  bytes(string, encoding[, errors]) -> bytes
 |  bytes(bytes_or_buffer) -> immutable copy of bytes_or_buffer
 |  bytes(int) -> bytes object of size given by the parameter initialized with null bytes
 |  bytes() -> empty bytes object
 |  
 |  Construct an immutable array of bytes from:
 |    - an iterable yielding integers in range(256)
 |    - a text string encoded using the specified encoding
 |    - any object implementing the buffer API.
 |    - an integer
 |  
 |  Methods defined here:
 |  
 |  __add__(self, value, /)
 |      Return self+value.
 |  
 |  __contains__(self, key, /)
 |      Return key in self.
 |  
 |  __eq__(self, value, /)
 |      Return self==value.
 |  
 |  __ge__(self, value, /)
 |      Return self>=value.
 |  
 |  __getattribute__(self, name, /)
 |      Return getattr(self, name).
 |  
 |  __getitem__(self, key, /)
 |      Return self[key].
 |  
 |  __getnewargs__

In [83]:
help(np.full)

Help on function full in module numpy.core.numeric:

full(shape, fill_value, dtype=None, order='C')
    Return a new array of given shape and type, filled with `fill_value`.
    
    Parameters
    ----------
    shape : int or sequence of ints
        Shape of the new array, e.g., ``(2, 3)`` or ``2``.
    fill_value : scalar
        Fill value.
    dtype : data-type, optional
        The desired data-type for the array  The default, `None`, means
         `np.array(fill_value).dtype`.
    order : {'C', 'F'}, optional
        Whether to store multidimensional data in C- or Fortran-contiguous
        (row- or column-wise) order in memory.
    
    Returns
    -------
    out : ndarray
        Array of `fill_value` with the given shape, dtype, and order.
    
    See Also
    --------
    zeros_like : Return an array of zeros with shape and type of input.
    ones_like : Return an array of ones with shape and type of input.
    empty_like : Return an empty array with shape and type of in

In [84]:
help(np.eye)

Help on function eye in module numpy.lib.twodim_base:

eye(N, M=None, k=0, dtype=<class 'float'>, order='C')
    Return a 2-D array with ones on the diagonal and zeros elsewhere.
    
    Parameters
    ----------
    N : int
      Number of rows in the output.
    M : int, optional
      Number of columns in the output. If None, defaults to `N`.
    k : int, optional
      Index of the diagonal: 0 (the default) refers to the main diagonal,
      a positive value refers to an upper diagonal, and a negative value
      to a lower diagonal.
    dtype : data-type, optional
      Data-type of the returned array.
    order : {'C', 'F'}, optional
        Whether the output should be stored in row-major (C-style) or
        column-major (Fortran-style) order in memory.
    
        .. versionadded:: 1.14.0
    
    Returns
    -------
    I : ndarray of shape (N,M)
      An array where all elements are equal to zero, except for the `k`-th
      diagonal, whose values are equal to one.
    
  

In [85]:
print(np.eye(3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [86]:
np.diag([1,2,3,4])

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [93]:
a=np.arange(5)
b=np.ones(5)
print(a,b)
print(a+b)
print(a-b)
print(a*b)
print(a/b)
print(a**b)
print(a//b)

[0 1 2 3 4] [1. 1. 1. 1. 1.]
[1. 2. 3. 4. 5.]
[-1.  0.  1.  2.  3.]
[0. 1. 2. 3. 4.]
[0. 1. 2. 3. 4.]
[0. 1. 2. 3. 4.]
[-0.  1.  2.  3.  4.]


In [95]:
np.random.randint(100)

18

In [97]:
np.random.randint(100)

17

In [98]:
np.random.randint(100,size=(5,2))

array([[ 0, 82],
       [68, 58],
       [80, 23],
       [55, 86],
       [15, 35]])

In [100]:
help(np.random.randn)

Help on built-in function randn:

randn(...) method of mtrand.RandomState instance
    randn(d0, d1, ..., dn)
    
    Return a sample (or samples) from the "standard normal" distribution.
    
    If positive, int_like or int-convertible arguments are provided,
    `randn` generates an array of shape ``(d0, d1, ..., dn)``, filled
    with random floats sampled from a univariate "normal" (Gaussian)
    distribution of mean 0 and variance 1 (if any of the :math:`d_i` are
    floats, they are first converted to integers by truncation). A single
    float randomly sampled from the distribution is returned if no
    argument is provided.
    
    This is a convenience function.  If you want an interface that takes a
    tuple as the first argument, use `numpy.random.standard_normal` instead.
    
    Parameters
    ----------
    d0, d1, ..., dn : int, optional
        The dimensions of the returned array, should be all positive.
        If no argument is given a single Python float is ret

In [103]:
np.random.randn(2,3)

array([[-0.31138825, -1.65606118, -0.38583847],
       [-0.71513054,  0.39870342, -0.51597181]])

In [105]:
np.random.rand(2,5)

array([[0.51608022, 0.00290005, 0.46042807, 0.97349921, 0.76986681],
       [0.53496468, 0.70550606, 0.75625546, 0.09649628, 0.5154756 ]])

In [106]:
dir(np.random)

['Lock',
 'RandomState',
 '__RandomState_ctor',
 '__all__',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '_numpy_tester',
 'absolute_import',
 'bench',
 'beta',
 'binomial',
 'bytes',
 'chisquare',
 'choice',
 'dirichlet',
 'division',
 'exponential',
 'f',
 'gamma',
 'geometric',
 'get_state',
 'gumbel',
 'hypergeometric',
 'info',
 'laplace',
 'logistic',
 'lognormal',
 'logseries',
 'mtrand',
 'multinomial',
 'multivariate_normal',
 'negative_binomial',
 'noncentral_chisquare',
 'noncentral_f',
 'normal',
 'np',
 'operator',
 'pareto',
 'permutation',
 'poisson',
 'power',
 'print_function',
 'rand',
 'randint',
 'randn',
 'random',
 'random_integers',
 'random_sample',
 'ranf',
 'rayleigh',
 'sample',
 'seed',
 'set_state',
 'shuffle',
 'standard_cauchy',
 'standard_exponential',
 'standard_gamma',
 'standard_normal',
 'standard_t',
 'test',
 'triangular',
 'uniform',
 'vonmises',
 'wald',
 'warnings

In [107]:
r=np.arange(10,20)
np.random.shuffle(r)
print(r)

[15 19 11 13 18 16 17 10 14 12]


In [108]:
a=np.arange(20)
a.reshape(5,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [109]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [110]:
a.reshape(10,2)

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19]])

In [111]:
a.reshape(4,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [112]:
help(np.resize)

Help on function resize in module numpy.core.fromnumeric:

resize(a, new_shape)
    Return a new array with the specified shape.
    
    If the new array is larger than the original array, then the new
    array is filled with repeated copies of `a`.  Note that this behavior
    is different from a.resize(new_shape) which fills with zeros instead
    of repeated copies of `a`.
    
    Parameters
    ----------
    a : array_like
        Array to be resized.
    
    new_shape : int or tuple of int
        Shape of resized array.
    
    Returns
    -------
    reshaped_array : ndarray
        The new array is formed from the data in the old array, repeated
        if necessary to fill out the required number of elements.  The
        data are repeated in the order that they are stored in memory.
    
    See Also
    --------
    ndarray.resize : resize an array in-place.
    
    Examples
    --------
    >>> a=np.array([[0,1],[2,3]])
    >>> np.resize(a,(2,3))
    array([[0, 1, 2]

In [113]:
np.resize(a,(13,2))

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [ 0,  1],
       [ 2,  3],
       [ 4,  5]])

In [114]:
z=np.arange(20)
z.resize((13,2))

In [115]:
z

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [ 0,  0],
       [ 0,  0],
       [ 0,  0]])

In [116]:
a2=np.arange(10).reshape(2,5)

In [117]:
np.expand_dims(a2,0)

array([[[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]]])

In [118]:
np.expand_dims(a2,1)

array([[[0, 1, 2, 3, 4]],

       [[5, 6, 7, 8, 9]]])

In [119]:
np.expand_dims(a2,1)

array([[[0, 1, 2, 3, 4]],

       [[5, 6, 7, 8, 9]]])

In [120]:
a2.flatten()

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [121]:
for i in a2:
    print(i)
    break

[0 1 2 3 4]


In [123]:
for i in np.arange(12).reshape(2,2,3):
    print(i)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]


In [124]:
print(a[0])
print(a[-1])

0
19


In [125]:
print(a[2:10])
print(a[2:12:3])

[2 3 4 5 6 7 8 9]
[ 2  5  8 11]


In [128]:
print(a[[1,10,3]])

[ 1 10  3]


In [130]:
a[[True,False]]

IndexError: boolean index did not match indexed array along dimension 0; dimension is 20 but corresponding boolean dimension is 2

In [131]:
a2=np.arange(20).reshape(5,4)
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [132]:
a2[0]

array([0, 1, 2, 3])

In [133]:
a2[-1]

array([16, 17, 18, 19])

In [136]:
a2[2,2]

10

In [137]:
a2[2][2]

10

In [138]:
a2[3,3]

15

In [143]:
a2[1:3,1:3]   #[row slicing,col slicing]

array([[ 5,  6],
       [ 9, 10]])

## Broadcating

In [ ]:
a=np.array([1,2,3])