In [2]:
import pandas as pd
import numpy as np
data=pd.read_csv('https://raw.githubusercontent.com/sumathi16/Machine-Learning-with-Python/master/data/Intel%20Data/Orange_Telecom_Churn_Data.csv')
data


state  account_length  area_code phone_number intl_plan voice_mail_plan  \
0       KS             128        415     382-4657        no             yes   
1       OH             107        415     371-7191        no             yes   
2       NJ             137        415     358-1921        no              no   
3       OH              84        408     375-9999       yes              no   
4       OK              75        415     330-6626       yes              no   
...    ...             ...        ...          ...       ...             ...   
4995    HI              50        408     365-8751        no             yes   
4996    WV             152        415     334-9736        no              no   
4997    DC              61        415     333-6861        no              no   
4998    DC             109        510     394-2206        no              no   
4999    VT              86        415     373-8058        no             yes   

      number_vmail_messages  total_day_minutes  total_day_calls  \
0                        25              265.1              110   
1                        26              161.6              123   
2                         0              243.4              114   
3                         0              299.4               71   
4                         0              166.7              113   
...                     ...                ...              ...   
4995                     40              235.7              127   
4996                      0              184.2               90   
4997                      0              140.6               89   
4998                      0              188.8               67   
4999                     34              129.4              102   

      total_day_charge  ...  total_eve_calls  total_eve_charge  \
0                45.07  ...               99             16.78   
1                27.47  ...              103             16.62   
2                41.38  ...              110             10.30   
3                50.90  ...               88              5.26   
4                28.34  ...              122             12.61   
...                ...  ...              ...               ...   
4995             40.07  ...              126             18.96   
4996             31.31  ...               73             21.83   
4997             23.90  ...              128             14.69   
4998             32.10  ...               92             14.59   
4999             22.00  ...              104             22.70   

      total_night_minutes  total_night_calls  total_night_charge  \
0                   244.7                 91               11.01   
1                   254.4                103               11.45   
2                   162.6                104                7.32   
3                   196.9                 89                8.86   
4                   186.9                121                8.41   
...                   ...                ...                 ...   
4995                297.5                116               13.39   
4996                213.6                113                9.61   
4997                212.4                 97                9.56   
4998                224.4                 89               10.10   
4999                154.8                100                6.97   

      total_intl_minutes  total_intl_calls  total_intl_charge  \
0                   10.0                 3               2.70   
1                   13.7                 3               3.70   
2                   12.2                 5               3.29   
3                    6.6                 7               1.78   
4                   10.1                 3               2.73   
...                  ...               ...                ...   
4995                 9.9                 5               2.67   
4996                14.7                 2               3.97   
4997                13.6                 4  

In [3]:
data.columns[data.dtypes==object]

Index(['state', 'phone_number', 'intl_plan', 'voice_mail_plan'], dtype='object')

In [4]:
data.columns[data.dtypes!=object]

Index(['account_length', 'area_code', 'number_vmail_messages',
       'total_day_minutes', 'total_day_calls', 'total_day_charge',
       'total_eve_minutes', 'total_eve_calls', 'total_eve_charge',
       'total_night_minutes', 'total_night_calls', 'total_night_charge',
       'total_intl_minutes', 'total_intl_calls', 'total_intl_charge',
       'number_customer_service_calls', 'churned'],
      dtype='object')

In [5]:
num_col=data[['account_length', 'area_code', 'number_vmail_messages',
       'total_day_minutes', 'total_day_calls', 'total_day_charge',
       'total_eve_minutes', 'total_eve_calls', 'total_eve_charge',
       'total_night_minutes', 'total_night_calls', 'total_night_charge',
       'total_intl_minutes', 'total_intl_calls', 'total_intl_charge',
       'number_customer_service_calls']]

In [6]:
cat_col=data[['state', 'phone_number', 'intl_plan', 'voice_mail_plan']]


In [7]:
num_col

account_length  area_code  number_vmail_messages  total_day_minutes  \
0                128        415                     25              265.1   
1                107        415                     26              161.6   
2                137        415                      0              243.4   
3                 84        408                      0              299.4   
4                 75        415                      0              166.7   
...              ...        ...                    ...                ...   
4995              50        408                     40              235.7   
4996             152        415                      0              184.2   
4997              61        415                      0              140.6   
4998             109        510                      0              188.8   
4999              86        415                     34              129.4   

      total_day_calls  total_day_charge  total_eve_minutes  total_eve_calls  \
0                 110             45.07              197.4               99   
1                 123             27.47              195.5              103   
2                 114             41.38              121.2              110   
3                  71             50.90               61.9               88   
4                 113             28.34              148.3              122   
...               ...               ...                ...              ...   
4995              127             40.07              223.0              126   
4996               90             31.31              256.8               73   
4997               89             23.90              172.8              128   
4998               67             32.10              171.7               92   
4999              102             22.00              267.1              104   

      total_eve_charge  total_night_minutes  total_night_calls  \
0                16.78                244.7                 91   
1                16.62                254.4                103   
2                10.30                162.6                104   
3                 5.26                196.9                 89   
4                12.61                186.9                121   
...                ...                  ...                ...   
4995             18.96                297.5                116   
4996             21.83                213.6                113   
4997             14.69                212.4                 97   
4998             14.59                224.4                 89   
4999             22.70                154.8                100   

      total_night_charge  total_intl_minutes  total_intl_calls  \
0                  11.01                10.0                 3   
1                  11.45                13.7                 3   
2                   7.32                12.2                 5   
3                   8.86                 6.6                 7   
4                   8.41                10.1                 3   
...                  ...                 ...               ...   
4995               13.39                 9.9                 5   
4996                9.61                14.7                 2   
4997                9.56                13.6                 4   
4998               10.10                 8.5                 6   
4999                6.97                 9.3                16   

      total_intl_charge  number_customer_service_calls  
0                  2.70                              1  
1                  3.70                              1  
2                  3.29                              0  
3                  1.78                              2  
4                  2.73                              3  
...                 ...                            ...  
4995               2.67                              2  
4996               3.97                              3  
4997               3.67          

In [8]:
cat_col

state phone_number intl_plan voice_mail_plan
0       KS     382-4657        no             yes
1       OH     371-7191        no             yes
2       NJ     358-1921        no              no
3       OH     375-9999       yes              no
4       OK     330-6626       yes              no
...    ...          ...       ...             ...
4995    HI     365-8751        no             yes
4996    WV     334-9736        no              no
4997    DC     333-6861        no              no
4998    DC     394-2206        no              no
4999    VT     373-8058        no             yes

[5000 rows x 4 columns]

In [9]:
target=data['churned']

In [10]:
target

0       False
1       False
2       False
3       False
4       False
        ...  
4995    False
4996     True
4997    False
4998    False
4999    False
Name: churned, Length: 5000, dtype: bool

In [11]:
# Get the numerical columns data only into num_features
num_features=num_col

In [12]:
num_features

account_length  area_code  number_vmail_messages  total_day_minutes  \
0                128        415                     25              265.1   
1                107        415                     26              161.6   
2                137        415                      0              243.4   
3                 84        408                      0              299.4   
4                 75        415                      0              166.7   
...              ...        ...                    ...                ...   
4995              50        408                     40              235.7   
4996             152        415                      0              184.2   
4997              61        415                      0              140.6   
4998             109        510                      0              188.8   
4999              86        415                     34              129.4   

      total_day_calls  total_day_charge  total_eve_minutes  total_eve_calls  \
0                 110             45.07              197.4               99   
1                 123             27.47              195.5              103   
2                 114             41.38              121.2              110   
3                  71             50.90               61.9               88   
4                 113             28.34              148.3              122   
...               ...               ...                ...              ...   
4995              127             40.07              223.0              126   
4996               90             31.31              256.8               73   
4997               89             23.90              172.8              128   
4998               67             32.10              171.7               92   
4999              102             22.00              267.1              104   

      total_eve_charge  total_night_minutes  total_night_calls  \
0                16.78                244.7                 91   
1                16.62                254.4                103   
2                10.30                162.6                104   
3                 5.26                196.9                 89   
4                12.61                186.9                121   
...                ...                  ...                ...   
4995             18.96                297.5                116   
4996             21.83                213.6                113   
4997             14.69                212.4                 97   
4998             14.59                224.4                 89   
4999             22.70                154.8                100   

      total_night_charge  total_intl_minutes  total_intl_calls  \
0                  11.01                10.0                 3   
1                  11.45                13.7                 3   
2                   7.32                12.2                 5   
3                   8.86                 6.6                 7   
4                   8.41                10.1                 3   
...                  ...                 ...               ...   
4995               13.39                 9.9                 5   
4996                9.61                14.7                 2   
4997                9.56                13.6                 4   
4998               10.10                 8.5                 6   
4999                6.97                 9.3                16   

      total_intl_charge  number_customer_service_calls  
0                  2.70                              1  
1                  3.70                              1  
2                  3.29                              0  
3                  1.78                              2  
4                  2.73                              3  
...                 ...                            ...  
4995               2.67                              2  
4996               3.97                              3  
4997               3.67          

In [13]:
# Split the data num_features and target into 80% for 
# training 20% for testing and random state 40
# store the results in X_train,X_test,y_train,y_test
from sklearn.model_selection import train_test_split

In [14]:
x_train,x_test,y_train,y_test=train_test_split(num_features,target,test_size=0.2,random_state=40)

In [15]:
print(x_train.shape)

(4000, 16)


In [16]:
print(x_test.shape)

(1000, 16)


In [17]:
print(y_train.shape)

(4000,)


In [18]:
print(y_test.shape)

(1000,)


In [19]:
# Train the KNN with X_train,y_train
from sklearn.neighbors import KNeighborsClassifier

In [20]:
knn=KNeighborsClassifier()
knn.fit(x_train,y_train)


KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                     weights='uniform')

In [21]:
help(KNeighborsClassifier)

Help on class KNeighborsClassifier in module sklearn.neighbors.classification:

class KNeighborsClassifier(sklearn.neighbors.base.NeighborsBase, sklearn.neighbors.base.KNeighborsMixin, sklearn.neighbors.base.SupervisedIntegerMixin, sklearn.base.ClassifierMixin)
 |  KNeighborsClassifier(n_neighbors=5, weights='uniform', algorithm='auto', leaf_size=30, p=2, metric='minkowski', metric_params=None, n_jobs=None, **kwargs)
 |  
 |  Classifier implementing the k-nearest neighbors vote.
 |  
 |  Read more in the :ref:`User Guide <classification>`.
 |  
 |  Parameters
 |  ----------
 |  n_neighbors : int, optional (default = 5)
 |      Number of neighbors to use by default for :meth:`kneighbors` queries.
 |  
 |  weights : str or callable, optional (default = 'uniform')
 |      weight function used in prediction.  Possible values:
 |  
 |      - 'uniform' : uniform weights.  All points in each neighborhood
 |        are weighted equally.
 |      - 'distance' : weight points by the inverse of th

In [49]:
#predict the output for X_train store it in variable y_out

y_out=knn.predict(x_train)

In [50]:
y_out

array([ True, False,  True, ...,  True,  True,  True])

In [51]:
# calculate the accuarcy for y_out,y_train
from sklearn.metrics import accuracy_score 

In [52]:
round(accuracy_score(y_out,y_train)*100,2)

29.75

In [53]:
#predict the output for X_test store it in variable y_pred

y_pred=knn.predict(x_test)
y_pred

array([ True,  True, False, False,  True,  True,  True,  True,  True,
       False,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True, False,  True,  True,  True, False,  True,
       False, False,  True,  True, False,  True,  True,  True,  True,
        True,  True, False,  True,  True,  True, False,  True,  True,
       False,  True,  True,  True,  True,  True,  True,  True, False,
        True,  True,  True, False,  True,  True, False,  True,  True,
        True,  True,  True, False,  True,  True,  True, False,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True, False,  True,  True,  True,  True, False,  True,  True,
       False,  True,  True,  True,  True,  True,  True,  True,  True,
       False,  True,  True,  True, False,  True,  True,  True,  True,
        True,  True,  True,  True, False,  True,  True,  True,  True,
        True, False,  True,  True,  True,  True,  True,  True,  True,
       False,  True,

In [54]:
# calculate the accuarcy for y_pred,y_test
round(accuracy_score(y_pred,y_test)*100,2)

28.8

2. Applying KNN with Numerical scaled Data Only


In [55]:
from sklearn.preprocessing import MinMaxScaler

In [56]:
sc=MinMaxScaler()
sc.fit(num_features)
num_features_sc=pd.DataFrame(sc.transform(num_features),columns=num_features.columns)

In [57]:
num_features_sc

account_length  area_code  number_vmail_messages  total_day_minutes  \
0           0.524793   0.068627               0.480769           0.754196   
1           0.438017   0.068627               0.500000           0.459744   
2           0.561983   0.068627               0.000000           0.692461   
3           0.342975   0.000000               0.000000           0.851778   
4           0.305785   0.068627               0.000000           0.474253   
...              ...        ...                    ...                ...   
4995        0.202479   0.000000               0.769231           0.670555   
4996        0.623967   0.068627               0.000000           0.524040   
4997        0.247934   0.068627               0.000000           0.400000   
4998        0.446281   1.000000               0.000000           0.537127   
4999        0.351240   0.068627               0.653846           0.368137   

      total_day_calls  total_day_charge  total_eve_minutes  total_eve_calls  \
0            0.666667          0.754183           0.542755         0.582353   
1            0.745455          0.459672           0.537531         0.605882   
2            0.690909          0.692436           0.333242         0.647059   
3            0.430303          0.851740           0.170195         0.517647   
4            0.684848          0.474230           0.407754         0.717647   
...               ...               ...                ...              ...   
4995         0.769697          0.670515           0.613143         0.741176   
4996         0.545455          0.523929           0.706076         0.429412   
4997         0.539394          0.399933           0.475117         0.752941   
4998         0.406061          0.537149           0.472092         0.541176   
4999         0.618182          0.368139           0.734396         0.611765   

      total_eve_charge  total_night_minutes  total_night_calls  \
0             0.542866             0.619494           0.520000   
1             0.537690             0.644051           0.588571   
2             0.333225             0.411646           0.594286   
3             0.170171             0.498481           0.508571   
4             0.407959             0.473165           0.691429   
...                ...                  ...                ...   
4995          0.613394             0.753165           0.662857   
4996          0.706244             0.540759           0.645714   
4997          0.475251             0.537722           0.554286   
4998          0.472016             0.568101           0.508571   
4999          0.734390             0.391899           0.571429   

      total_night_charge  total_intl_minutes  total_intl_calls  \
0               0.619584               0.500              0.15   
1               0.644344               0.685              0.15   
2               0.411930               0.610              0.25   
3               0.498593               0.330              0.35   
4               0.473270               0.505              0.15   
...                  ...                 ...               ...   
4995            0.753517               0.495              0.25   
4996            0.540799               0.735              0.10   
4997            0.537985               0.680              0.20   
4998            0.568374               0.425              0.30   
4999            0.392234               0.465              0.80   

      total_intl_charge  number_customer_service_calls  
0              0.500000                       0.111111  
1              0.685185                       0.111111  
2              0.609259                       0.000000  
3              0.329630                       0.222222  
4              0.505556                       0.333333  
...                 ...                            ...  
4995           0.494444                       0.222222  
4996           0.735185                       0.333333  
4997           0.679630          

In [132]:
# 

In [133]:

x_train_sc,x_test_sc,y_train_sc,y_test_sc=train_test_split(num_features_sc,target,test_size=0.2,random_state=40)

In [134]:
print(x_train_sc.shape)

(4000, 16)


In [135]:
print(x_test_sc)

      account_length  area_code  number_vmail_messages  total_day_minutes  \
4088        0.425620   1.000000               0.000000           0.318350   
2080        0.446281   0.068627               0.000000           0.569275   
41          0.553719   0.000000               0.788462           0.492461   
796         0.462810   0.068627               0.615385           0.513229   
354         0.260331   0.000000               0.000000           0.671977   
...              ...        ...                    ...                ...   
970         0.347107   0.068627               0.000000           0.501849   
3716        0.173554   0.068627               0.000000           0.525747   
315         0.157025   0.000000               0.000000           0.171835   
2873        0.140496   0.000000               0.000000           0.451209   
846         0.392562   0.068627               0.000000           0.513798   

      total_day_calls  total_day_charge  total_eve_minutes  total_eve_calls

In [136]:
print(y_train_sc.shape)

(4000,)


In [137]:
print(y_test_sc.shape)

(1000,)


In [138]:
knn=KNeighborsClassifier()
knn.fit(x_train_sc,y_train_sc)


KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                     weights='uniform')

In [139]:
y_out_sc=knn.predict(x_train_sc)

In [140]:
y_out_sc

array([False, False, False, ..., False,  True, False])

In [141]:
from sklearn.metrics import accuracy_score 

In [142]:
accuracy_score(y_out_sc,y_train_sc)

0.91725

In [143]:
y_pred_sc=knn.predict(x_test_sc)

In [144]:
y_pred_sc

array([False, False, False, False,  True, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
        True, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False,  True, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False,

In [145]:
accuracy_score(y_pred_sc,y_test_sc)

0.887

3.Apply KNN with five numerical columns

In [ ]:
# Choose five columns in features 
 # Give selected column names



In [167]:


import pandas as pd

In [170]:

sel_feature_names=data.loc[:,['account_length','area_code','number_vmail_messages','total_day_minutes','total_day_calls']]

In [171]:
sel_feature_names

account_length  area_code  number_vmail_messages  total_day_minutes  \
0                128        415                     25              265.1   
1                107        415                     26              161.6   
2                137        415                      0              243.4   
3                 84        408                      0              299.4   
4                 75        415                      0              166.7   
...              ...        ...                    ...                ...   
4995              50        408                     40              235.7   
4996             152        415                      0              184.2   
4997              61        415                      0              140.6   
4998             109        510                      0              188.8   
4999              86        415                     34              129.4   

      total_day_calls  
0                 110  
1                 123  
2                 114  
3                  71  
4                 113  
...               ...  
4995              127  
4996               90  
4997               89  
4998               67  
4999              102  

[5000 rows x 5 columns]

In [172]:
selected_features=sel_feature_names

In [173]:
selected_features

account_length  area_code  number_vmail_messages  total_day_minutes  \
0                128        415                     25              265.1   
1                107        415                     26              161.6   
2                137        415                      0              243.4   
3                 84        408                      0              299.4   
4                 75        415                      0              166.7   
...              ...        ...                    ...                ...   
4995              50        408                     40              235.7   
4996             152        415                      0              184.2   
4997              61        415                      0              140.6   
4998             109        510                      0              188.8   
4999              86        415                     34              129.4   

      total_day_calls  
0                 110  
1                 123  
2                 114  
3                  71  
4                 113  
...               ...  
4995              127  
4996               90  
4997               89  
4998               67  
4999              102  

[5000 rows x 5 columns]

In [ ]:
from sklearn.model_selection import train_test_split


In [179]:
x_train_sel,x_test_sel,y_train_sel,y_test_sel=train_test_split(selected_features,target,test_size=0.2,random_state=40)

In [184]:
print(x_train_sel.shape)

(4000, 5)


In [186]:
print(y_train_sel.shape)

(4000,)


In [187]:
# Train the KNN with X_train_sel,y_train_sel

from sklearn.neighbors import KNeighborsClassifier

In [183]:
knn=KNeighborsClassifier()
knn.fit(x_train_sel,y_train_sel)


KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                     weights='uniform')

In [192]:
#predict the output for X_train_sel store it in variable y_out

y_out_sel=knn.predict(x_train_sel)

In [193]:
y_out_sel

array([False, False, False, ..., False, False, False])

In [195]:
# calculate the accuarcy for y_out,y_train
from sklearn.metrics import accuracy_score

In [209]:
round(accuracy_score(y_out_sel,y_train_sel)*100,2)

88.78

In [204]:
#predict the output for X_test_sel store it in variable y_pred
y_pred_sel=knn.predict(x_test_sel)

In [205]:
y_pred_sel

array([ True, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False,  True, False, False, False,  True,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False,  True,  True, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False,  True, False, False, False, False, False, False, False,
       False, False,

In [208]:
# calculate the accuarcy for y_pred,y_test
round(accuracy_score(y_pred_sel,y_test_sel)*100,2)

86.1