## TIME COMPARISION

In [4]:
import time
import numpy as np
start = time.time()
l=[x*x for x in range(100000)]
end=time.time()
print('time with lists:',start-end)
start = time.time()
a=np.arange(100000)
a=a*a
end=time.time()
print('time with lists:',end-start)

time with lists: -0.04686331748962402
time with lists: 0.0


## Trignometric Functions

In [6]:
a=np.random.randint(100,size=23)
np.sin(a)

array([-0.95892427, -0.53657292,  0.68326171,  0.51397846, -0.90557836,
       -0.76825466,  0.43616476, -0.44411267,  0.43616476, -0.44411267,
       -0.64353813, -0.99999021, -0.99388865,  0.99287265,  0.27090579,
       -0.92345845, -0.98803162, -0.94828214,  0.31322878, -0.90557836,
        0.65028784,  0.86006941, -0.98803162])

In [7]:
np.sin(3.14/2)

0.9999996829318346

In [8]:
np.arcsin(1)

1.5707963267948966

In [9]:
np.rad2deg(1.57928722766)

90.48649278383441

In [10]:
np.deg2rad(90)

1.5707963267948966

In [11]:
import math
math.sin(a)

TypeError: only size-1 arrays can be converted to Python scalars

In [13]:
math.sin([2,3])

TypeError: must be real number, not list

## Log and Exponential Functions

In [14]:
print(np.log(2))
print(np.log(1))
print(np.log(np.exp(1)))

0.6931471805599453
0.0
1.0


In [16]:
print(np.log2(2))
print(np.log2(32))

1.0
5.0


In [19]:
np.log1p(2)
#np.log1p(x) = np.log(1+x)

1.0986122886681098

In [20]:
np.log(2+1)

1.0986122886681098

In [21]:
print(np.exp(1))
print(np.exp2(2))

2.718281828459045
4.0


In [22]:
print(np.expm1(5))
print(np.exp(5)-1)
#np.exmp1

147.4131591025766
147.4131591025766


## Statistics

In [23]:
a=np.random.randint(100,size=5)
a

array([42, 79, 45, 28, 66])

In [24]:
print(a.sum())
print(np.sum(a))
print(np.mean(a))
print(np.median(a))
print(np.std(a))

260
260
52.0
45.0
18.16590212458495


In [25]:
print(np.quantile(a,0.25))
print(np.quantile(a,0.5))
print(np.quantile(a,0.75))

AttributeError: module 'numpy' has no attribute 'quantile'

In [26]:
a=np.arange(5)
b=np.arange(4)
a+b

ValueError: operands could not be broadcast together with shapes (5,) (4,) 

In [28]:
a=np.arange(10).reshape(5,2)
b=np.arange(2)
a+b

array([[ 0,  2],
       [ 2,  4],
       [ 4,  6],
       [ 6,  8],
       [ 8, 10]])

In [39]:
a=np.arange(15).reshape(5,3,1)
b=np.arange(5)
a+b

array([[[ 0,  1,  2,  3,  4],
        [ 1,  2,  3,  4,  5],
        [ 2,  3,  4,  5,  6]],

       [[ 3,  4,  5,  6,  7],
        [ 4,  5,  6,  7,  8],
        [ 5,  6,  7,  8,  9]],

       [[ 6,  7,  8,  9, 10],
        [ 7,  8,  9, 10, 11],
        [ 8,  9, 10, 11, 12]],

       [[ 9, 10, 11, 12, 13],
        [10, 11, 12, 13, 14],
        [11, 12, 13, 14, 15]],

       [[12, 13, 14, 15, 16],
        [13, 14, 15, 16, 17],
        [14, 15, 16, 17, 18]]])

In [40]:
a=np.arange(15).reshape(5,3)
print(np.sum(a))
print(np.sum(a,axis=0))
print(np.sum(a,axis=1))

105
[30 35 40]
[ 3 12 21 30 39]


In [41]:
np.random.seed(0)
a=np.random.randint(50,size=10)
b=np.random.randint(58,size=10)
print(a,b)

[44 47  0  3  3 39  9 19 21 36] [23  6 24 24 12  1 38 39 23 46]


In [42]:
help(np.random.seed)

Help on built-in function seed:

seed(...) method of mtrand.RandomState instance
    seed(seed=None)
    
    Seed the generator.
    
    This method is called when `RandomState` is initialized. It can be
    called again to re-seed the generator. For details, see `RandomState`.
    
    Parameters
    ----------
    seed : int or 1-d array_like, optional
        Seed for `RandomState`.
        Must be convertible to 32 bit unsigned integers.
    
    See Also
    --------
    RandomState



In [43]:
def maxnumber(n1,n2):
    if n1>n2:
        return n1
    else:
        return n2
maxnumber(5,44)

44

In [45]:
maxnumber_vec=np.vectorize(maxnumber)
maxnumber_vec(a,b)

array([44, 47, 24, 24, 12, 39, 38, 39, 23, 46])

## Stacking

In [46]:
a=np.arange(6)
b=np.arange(6)
np.hstack([a,b])

array([0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5])

In [47]:
np.vstack([a,b])

array([[0, 1, 2, 3, 4, 5],
       [0, 1, 2, 3, 4, 5]])

In [50]:
a=np.arange(6).reshape(2,3)
a=np.arange(6).reshape(2,1)
b
a

ValueError: cannot reshape array of size 6 into shape (2,1)

In [52]:
np.linalg.det(np.eye(2))

1.0

In [53]:
np.linalg.det(np.array([[1,2],[5,7]]))

-2.999999999999999

In [54]:
np.linalg.inv(np.array([[1,2],[5,7]]))

array([[-2.33333333,  0.66666667],
       [ 1.66666667, -0.33333333]])

In [56]:
np.linalg.matrix_rank(np.array([[1,2],[5,7]]))

2

- np.dot
- np.matmul

In [63]:
s=input()
c=0
for i in s:
    if i=='a' or i=='e' or i=='i' or i=='o' or i=='u':
      c+=1         
print(c)

hi
1


In [2]:
import datetime
o=open('data.txt')
data=o.read()
data=eval(data)
data

[{'attendance': 'P',
  'session': 'FN',
  'date': datetime.date(2019, 12, 21),
  'level': 3,
  'student_id': 520},
 {'attendance': 'P',
  'session': 'FN',
  'date': datetime.date(2019, 12, 21),
  'level': 3,
  'student_id': 521},
 {'attendance': 'P',
  'session': 'FN',
  'date': datetime.date(2019, 12, 21),
  'level': 3,
  'student_id': 523},
 {'attendance': 'P',
  'session': 'FN',
  'date': datetime.date(2019, 12, 21),
  'level': 3,
  'student_id': 524},
 {'attendance': 'P',
  'session': 'FN',
  'date': datetime.date(2019, 12, 21),
  'level': 3,
  'student_id': 530},
 {'attendance': 'P',
  'session': 'FN',
  'date': datetime.date(2019, 12, 21),
  'level': 3,
  'student_id': 531},
 {'attendance': 'A',
  'session': 'FN',
  'date': datetime.date(2019, 12, 21),
  'level': 3,
  'student_id': 533},
 {'attendance': 'P',
  'session': 'FN',
  'date': datetime.date(2019, 12, 21),
  'level': 3,
  'student_id': 534},
 {'attendance': 'P',
  'session': 'FN',
  'date': datetime.date(2019, 12, 21),
 

In [3]:
l=[]
for i in data:
    if i['student_id'] not in l:
        l.append(i['student_id'])
print(l)

[520, 521, 523, 524, 530, 531, 533, 534, 535, 536, 539, 540, 541, 544, 546, 549, 550, 551, 552, 555, 556, 557, 558, 560, 561, 564, 565, 568, 569, 572, 574, 575, 576, 578, 579, 580, 904, 905, 906, 908, 909, 911, 912, 914, 915, 917, 918, 919, 921, 923, 924, 926, 927, 928, 929, 930, 931, 932, 933, 934, 935, 936, 937, 938, 939, 940, 941, 942, 943, 944, 945, 946, 947, 948, 949, 950, 951, 953, 955, 956, 957, 958, 959, 960, 961, 962, 963, 964, 965, 966, 967, 3392, 3391, 3390, 781, 803, 1042, 1055, 1066, 1081, 1091, 774, 775, 776, 777, 778, 827, 1054, 783, 784, 785, 786, 787, 788, 789, 791, 792, 793, 795, 796, 797, 798, 800, 805, 806, 807, 808, 809, 810, 811, 812, 813, 814, 815, 816, 817, 818, 820, 821, 822, 823, 824, 825, 826, 828, 829, 830, 831, 832, 833, 834, 835, 836, 837, 838, 1033, 1035, 1036, 1037, 1038, 1039, 1040, 1041, 1043, 1044, 1046, 1047, 1049, 1050, 1051, 1052, 1053, 1056, 1057, 1058, 1059, 1060, 1061, 1062, 1064, 1065, 1067, 1068, 1069, 1070, 1071, 1072, 1073, 1074, 1075, 1076,

In [6]:
l.sort()
print(l)

[457, 459, 460, 461, 462, 463, 464, 466, 467, 468, 469, 471, 472, 473, 474, 475, 476, 477, 478, 480, 482, 484, 485, 486, 487, 489, 490, 491, 492, 493, 494, 495, 496, 497, 498, 499, 500, 501, 505, 506, 507, 508, 509, 510, 511, 512, 513, 515, 516, 517, 518, 520, 521, 523, 524, 530, 531, 533, 534, 535, 536, 539, 540, 541, 544, 546, 549, 550, 551, 552, 555, 556, 557, 558, 560, 561, 563, 564, 565, 568, 569, 572, 574, 575, 576, 578, 579, 580, 774, 775, 776, 777, 778, 781, 783, 784, 785, 786, 787, 788, 789, 791, 792, 793, 795, 796, 797, 798, 800, 803, 805, 806, 807, 808, 809, 810, 811, 812, 813, 814, 815, 816, 817, 818, 820, 821, 822, 823, 824, 825, 826, 827, 828, 829, 830, 831, 832, 833, 834, 835, 836, 837, 838, 904, 905, 906, 908, 909, 911, 912, 914, 915, 917, 918, 919, 921, 923, 924, 926, 927, 928, 929, 930, 931, 932, 933, 934, 935, 936, 937, 938, 939, 940, 941, 942, 943, 944, 945, 946, 947, 948, 949, 950, 951, 953, 955, 956, 957, 958, 959, 960, 961, 962, 963, 964, 965, 966, 967, 1033, 103

In [7]:
for i in l:
    dic={'student_id':i}
    li=[]
    for j in data:
        if(i==j['student_id']):
            li.append(j['attendance'])
        dic['attendance']=li
           
    print(dic)
    

{'student_id': 457, 'attendance': ['P', 'P', 'P', 'P', 'P', 'P']}
{'student_id': 459, 'attendance': ['P', 'P', 'P', 'P', 'P', 'P']}
{'student_id': 460, 'attendance': ['P', 'P', 'P', 'P', 'P', 'P']}
{'student_id': 461, 'attendance': ['A', 'P', 'P', 'P', 'P', 'P']}
{'student_id': 462, 'attendance': ['P', 'P', 'P', 'P', 'P', 'P']}
{'student_id': 463, 'attendance': ['P', 'P', 'P', 'P', 'P', 'P']}
{'student_id': 464, 'attendance': ['P', 'P', 'P', 'P', 'P', 'P']}
{'student_id': 466, 'attendance': ['P', 'P', 'P', 'P', 'P', 'P']}
{'student_id': 467, 'attendance': ['P', 'P', 'P', 'P', 'P', 'P']}
{'student_id': 468, 'attendance': ['A', 'A', 'P', 'P', 'P', 'A']}
{'student_id': 469, 'attendance': ['P', 'P', 'P', 'P', 'P', 'P']}
{'student_id': 471, 'attendance': ['P', 'P', 'P', 'P', 'P', 'P']}
{'student_id': 472, 'attendance': ['P', 'P', 'P', 'P', 'P', 'P']}
{'student_id': 473, 'attendance': ['P', 'P', 'P', 'P', 'P', 'A']}
{'student_id': 474, 'attendance': ['P', 'P', 'P', 'P', 'P', 'P']}
{'student_

{'student_id': 941, 'attendance': ['P', 'P', 'P', 'P', 'P', 'P']}
{'student_id': 942, 'attendance': ['P', 'P', 'P', 'P', 'P', 'P']}
{'student_id': 943, 'attendance': ['P', 'P', 'P', 'P', 'P', 'P']}
{'student_id': 944, 'attendance': ['P', 'P', 'P', 'P', 'P', 'P']}
{'student_id': 945, 'attendance': ['P', 'P', 'P', 'P', 'P', 'P']}
{'student_id': 946, 'attendance': ['P', 'P', 'P', 'P', 'P', 'P']}
{'student_id': 947, 'attendance': ['P', 'P', 'P', 'P', 'P', 'P']}
{'student_id': 948, 'attendance': ['P', 'A', 'P', 'P', 'P', 'P']}
{'student_id': 949, 'attendance': ['P', 'P', 'P', 'P', 'P', 'P']}
{'student_id': 950, 'attendance': ['P', 'P', 'P', 'P', 'P', 'P']}
{'student_id': 951, 'attendance': ['P', 'P', 'P', 'P', 'P', 'P']}
{'student_id': 953, 'attendance': ['P', 'P', 'P', 'P', 'P', 'P']}
{'student_id': 955, 'attendance': ['P', 'P', 'P', 'P', 'P', 'P']}
{'student_id': 956, 'attendance': ['P', 'P', 'P', 'P', 'P', 'P']}
{'student_id': 957, 'attendance': ['P', 'P', 'P', 'P', 'P', 'P']}
{'student_